name: Java Application CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: echo "ACTION=${{ secrets.ACTION }}" >> $GITHUB_ENV

      - name: Checkout repository
        if: env.ACTION == 'create'
        uses: actions/checkout@v3
        with:
          repository: Megaax/javaApp-CICD
          ref: main

      - name: Set up JDK 11
        if: env.ACTION == 'create'
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Unit Test with Maven
        if: env.ACTION == 'create'
        run: mvn test

      - name: Integration Test with Maven
        if: env.ACTION == 'create'
        run: mvn verify -DskipUnitTests

      - name: SonarQube Scan
        if: env.ACTION == 'create'
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=my-Java-web-app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        if: env.ACTION == 'create'
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Show SonarQube Quality Gate Status
        if: env.ACTION == 'create'
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
