name: Java Application CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          echo "ACTION=${{ secrets.ACTION }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Megaax/javaApp-CICD
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"

      - name: Unit Test with Maven
        run: mvn test

      - name: Integration Test with Maven
        run: mvn verify -DskipUnitTests